"""recuperar-contrasena

Revision ID: 81a3a9b0242f
Revises: d04982833a62
Create Date: 2026-02-12 22:22:59.180941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81a3a9b0242f'
down_revision = 'd04982833a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo_recuperacion', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('codigo_recuperacion_expiracion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('codigo_recuperacion_expiracion')
        batch_op.drop_column('codigo_recuperacion')

    # ### end Alembic commands ###
